services:
  - type: web
    name: GeodEdge
    env: python
    plan: free
    buildCommand: |
      npm install
      npx --yes tailwindcss -i ./static/src/input.css -o ./static/dist/output.css --minify
      pip install -r requirements.txt
    startCommand: python app.py
