services:
  - type: web
    name: zhongli
    env: python
    plan: free
    buildCommand: |
      rm -rf node_modules
      npm install --production=false --force
      mkdir -p static/dist
      # Robust Tailwind build with explicit installation
      if [ ! -f node_modules/.bin/tailwindcss ]; then
        npm install tailwindcss@latest
      fi
      ./node_modules/.bin/tailwindcss -i ./static/src/input.css -o ./static/dist/output.css --minify
      poetry install --no-dev
      poetry run pip install gunicorn
    startCommand: |
      poetry run gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT app:app