services:
  - type: web
    name: GeodEdge
    env: python
    plan: free
    buildCommand: |
      chmod -R +x node_modules/.bin
      npm ci
      npm run build:css
      pip install -r requirements.txt
    startCommand: python app.py