services:
  - type: web
    name: GeodEdge
    env: python
    plan: free
    buildCommand: |
      npm install --production=false
      mkdir -p static/dist
      chmod -R +x node_modules/.bin
      ./node_modules/.bin/tailwindcss -i ./static/src/input.css -o ./static/dist/output.css --minify
      pip install -r requirements.txt
    startCommand: python app.py