services:
  - type: web
    name: zhongli
    env: python
    plan: free
    buildCommand: |
      npm install --production=false --force
      mkdir -p static/dist
      (./node_modules/.bin/tailwindcss -i ./static/src/input.css -o ./static/dist/output.css --minify || npx tailwindcss@latest -i ./static/src/input.css -o ./static/dist/output.css --minify)
      poetry install --no-dev
      poetry run pip install gunicorn
    startCommand: |
      poetry run gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT app:app