services:
  - type: web
    name: flask-tailwind
    env: python
    plan: free
    buildCommand: |
      rm -rf node_modules
      npm install --production=false --force
      mkdir -p static/dist
      npm install tailwindcss@latest @tailwindcss/cli
      npx tailwindcss -i ./static/src/input.css -o ./static/dist/output.css --minify
      pip install -r requirements.txt
      pip install supabase
      pip install gunicorn
    startCommand: |
      gunicorn --worker-tmp-dir /dev/shm --bind 0.0.0.0:$PORT app:app