services:
  - type: web
    name: GeodEdge
    env: python
    plan: free
    buildCommand: |
      npm install
      npm run build:css
      pip install -r requirements.txt
    startCommand: python app.py
